run:
  timeout: 5m
  tests: true
  concurrency: 4
linters:
  presets:
    - bugs
    - error
    - style
    - import
    - performance
    - complexity
    - module
    - test
    - comment
  disable:
    - depguard
    - exhaustruct
    - tagliatelle
    - gci
    - gomoddirectives
issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoglobals
        - wrapcheck
        - gomnd
    - path: internal/util/
      linters:
        - gomnd