#!/bin/bash

IMAGE="chainlink:latest"
ENVIRONMENT="default"
KEY="default"
KEYPREFIX="default"
COUNT=4 # creates 4 participant nodes
AMOUNT="10e17" # on the ETH network this is 0.1 ETH
CREATE_ADDRESS=true
FUND_ADDRESS=true

automation-cli network bootstrap add ${IMAGE} --environment=${ENVIRONMENT}

for (( i=1 ; i<=${COUNT} ; i++ )); 
do
    nodeKey="${KEYPREFIX}-${i}"

    if [ "${CREATE_ADDRESS}" = true ] ; then
        automation-cli key create ${nodeKey}
    fi

    automation-cli network participant add ${IMAGE} --count=1 --environment=${ENVIRONMENT} --key=${nodeKey}

    if [ "${FUND_ADDRESS}" = true ] ; then
        automation-cli network fund ${i} ${AMOUNT} --environment=${ENVIRONMENT} --key=${KEY}
    fi
done

echo "node participants:"

automation-cli network list --environment=${ENVIRONMENT}